config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  devise_for :users
  resources :contestants
  resources :workshops
  

  namespace :api,defaults: {format: :json} do
    namespace :v1 do
        resources :contestants
        get 'workshops/validate'
    end
  end

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base

	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
	
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery unless: -> { request.format.json? }
  skip_before_filter :verify_authenticity_token
end

app/controllers/api/v1/contestant_controller.rb
class Api::V1::ContestantsController < Api::V1::ApplicationController
  before_action :set_contestant, only: [:show, :edit, :update, :destroy]

  # GET /contestants
  # GET /contestants.json
  def index
    @contestants = Contestant.all
  end

  # GET /contestants/1
  # GET /contestants/1.json
  def show
  end

  # GET /contestants/new
  def new
    @contestant = Contestant.new
  end

  # GET /contestants/1/edit
  def edit
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(contestant_params)

    
      if @contestant.save
         render json:  @contestant
      else
        render json: @contestant.errors
      end
    
  end

  # PATCH/PUT /contestants/1
  # PATCH/PUT /contestants/1.json
  def update
    respond_to do |format|
      if @contestant.update(contestant_params)
        format.html { redirect_to @contestant, notice: 'Contestant was successfully updated.' }
        format.json { render :show, status: :ok, location: @contestant }
      else
        format.html { render :edit }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contestants/1
  # DELETE /contestants/1.json
  def destroy
    @contestant.destroy
    respond_to do |format|
      format.html { redirect_to contestants_url, notice: 'Contestant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contestant
      @contestant = Contestant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contestant_params
      params.require(:contestant).permit(:learn,:url_image,:workshop,:userid,:asistentes)
    end
end

app/controllers/api/v1/workshops_controller.rb
class Api::V1::WorkshopsController < Api::V1::ApplicationController

  def validate
    @workshops = Workshop.where(folio: params[:folio])

    json_reponse = []
    i = 0
    @workshops.each do |workshop|
      dias = Time.now - workshop.created_at
      if dias <= 86400
         json_reponse[i]={
          id: workshop.id,
          folio: workshop.folio,
          dias: dias
        }
        i=i+1

        render json: json_reponse
      else
      end
    end
    

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  before_action :set_contestant, only: [:show, :edit, :update, :destroy]


  # GET /contestants/new
  def new
    @contestant = Contestant.new
  end

  # GET /contestants/1/edit
  def edit
  end

  # POST /contestants
  # POST /contestants.json
  def create
    @contestant = Contestant.new(contestant_params)

    respond_to do |format|
      if @contestant.save
        format.html { redirect_to @contestant, notice: 'Contestant was successfully created.' }
        format.json { render :show, status: :created, location: @contestant }
      else
        format.html { render :new }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end
    def update
    respond_to do |format|
      if @contestant.update(contestant_params)
        format.html { redirect_to @contestant, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @contestant }
      else
        format.html { render :edit }
        format.json { render json: @contestant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contestant
      @contestant = Contestant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contestant_params
      params.require(:contestant).permit(:learn,:image,:userid,:workshop)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
  before_action :set_workshop, only: [:show, :edit, :update, :destroy]

  # GET /workshops
  # GET /workshops.json
  def index
    @workshops = Workshop.all.paginate(page: params[:page], per_page: 7)  
  end

  # GET /workshops/1
  # GET /workshops/1.json
  def show
    @asistentes = Contestant.where(workshop: @workshop.id).where(userid: 0)
    @docente = Contestant.where(workshop: @workshop.id).where(userid: "1")

  end

  # GET /workshops/new
  def new
    @workshop = Workshop.new
  end

  # GET /workshops/1/edit
  def edit
  end

  # POST /workshops
  # POST /workshops.json
  def create
    @workshop = Workshop.new(workshop_params)

    respond_to do |format|
      if @workshop.save
        format.html { redirect_to @workshop, notice: 'Workshop was successfully created.' }
        format.json { render :show, status: :created, location: @workshop }
      else
        format.html { render :new }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workshops/1
  # PATCH/PUT /workshops/1.json
  def update
    respond_to do |format|
      if @workshop.update(workshop_params)
        format.html { redirect_to @workshop, notice: 'Workshop was successfully updated.' }
        format.json { render :show, status: :ok, location: @workshop }
      else
        format.html { render :edit }
        format.json { render json: @workshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workshops/1
  # DELETE /workshops/1.json
  def destroy
    @workshop.destroy
    respond_to do |format|
      format.html { redirect_to workshops_url, notice: 'Workshop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workshop
      @workshop = Workshop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def workshop_params
      params.require(:workshop).permit(:folio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/contestants/_form.html.erb
<div class="row">
  <div class="col s12 m12 l12">
    
  </div>
</div>




<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :learn %><br>
    <%= f.number_field :learn %>
  </div>
  <div class="field">

    <%= f.number_field :workshop %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contestants/edit.html.erb
<h1>Editing Contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

app/views/contestants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contestants</h1>

<table>
  <thead>
    <tr>
      <th>Learn</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contestants.each do |contestant| %>
      <tr>
        <td><%= contestant.learn %></td>
        <td><%= link_to 'Show', contestant %></td>
        <td><%= link_to 'Edit', edit_contestant_path(contestant) %></td>
        <td><%= link_to 'Destroy', contestant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contestant', new_contestant_path %>

app/views/contestants/new.html.erb
<h1>New Contestant</h1>

<%= render 'form' %>

<%= link_to 'Back', contestants_path %>

app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Learn:</strong>
  <%= @contestant.learn %>
</p>



<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CorisApiV2</title>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
   <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
</head>
<body class="grey lighten-5" >

	<%=render 'partials/nav' %>

	
  	<%if notice%>
	    <div id="notice_wrapper">
	      <p class="notice"><%=notice%></p>
	    </div>
	<%elsif alert%>
	    <div id="notice_wrapper">
	      <p class="alert"><%=alert%></p>
	    </div>
	<%end%>
	<div class="container">
		<div class="padding-largo card">
			<%= yield %>	
		</div>
	</div>

    <footer class="page-footer bottom primary">
        <div class="footer-copyright">
            <div class="container">
            © 2016 Copyright Text
            </div>
        </div>
    </footer>

<script src="http://code.jquery.com/jquery-2.2.0.min.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <script>
   $('.datepicker').pickadate({
    format: "yyyy-mm-dd"
   });
   $(".button-collapse").sideNav();
  </script>
  <script>
  $(document).ready(function() {

    setTimeout(function() {
      $("#notice_wrapper").slideUp();
    }, 3000);
  });
</script>
</body>
</html>

app/views/partials/_nav.html.erb
  <nav class="primary" >
    <div class="nav-wrapper container">
      <a href="#!" class="brand-logo">Logo</a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        
        <%if user_signed_in?%>
        <li><%= link_to 'Talleres', workshops_path%></li>
          <li><%= link_to "Cerrar Sesion", destroy_user_session_path, method: :delete, id: 'salida' %> </li>
          
        <%end%>
      </ul>
      <ul class="side-nav" id="mobile-demo">
      </ul>
    </div>
  </nav>

app/views/welcome/index.html.erb
<div class="row">
	<h3 class="center-align">
		Bienvenido
	</h3>
</div>

app/views/workshops/_form.html.erb
<%= form_for(@workshop) do |f| %>
  <% if @workshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workshop.errors.count, "error") %> prohibited this workshop from being saved:</h2>

      <ul>
      <% @workshop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
  <div class="input-field col s12 m12 l4 offset-l4">
    <%= f.label :folio %>
    <%= f.text_field :folio %>
  </div>
</div>

  <div class="row">
  <div class="center-align">
    <%= f.submit @msg, class: 'btn dark'%>
  </div>
    
  </div>
<% end %>

app/views/workshops/edit.html.erb
<div class="row">
	<div class="row">
		<h3 class="center-align">
			Editar Taller
		</h3>
	</div>
	<div class="row">
		<%= render 'form' %>

	</div>
</div>

app/views/workshops/index.html.erb
<div class="row">
  <div class="col s12 m12 l12">
      <div class="row">
    <h3 class="center-align">Talleres</h3>

    <div class="row ">
      <div class="col s12 m12 l12 padding-largo">
              <table class="table">
        <thead>
          <tr>
            <th>Folio</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @workshops.each do |workshop| %>
            <tr>
              <td><%= workshop.folio %></td>
              <td class="right" ><%= link_to '', workshop, class: 'btn blue ion-search' %>
              <%= link_to '', edit_workshop_path(workshop), class: 'btn dark ion-edit' %>
              <%= link_to '', workshop, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn red ion-trash-b' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>  
      </div>
    </div>

    <div class="row">
       <%= will_paginate @workshops %>
    </div>

    <div class="row">
      <div class="col s12 m12 l12">
        
      <%= link_to 'Nuevo Taller', new_workshop_path, class: 'btn accent' %>
        
      </div>
    </div>

  </div>
  </div>
</div>

app/views/workshops/new.html.erb
<h1>New Workshop</h1>

<%= render 'form' %>

<%= link_to 'Back', workshops_path %>

app/views/workshops/show.html.erb
<div class="row">
	<div class="row">
		<h3 class="center-align">
			Detalles del Taller
		</h3>
	</div>
	<div class="row">
		<p class="padding-largo">
		  <strong>Folio:</strong>
		  <%= @workshop.folio %>
		</p>
	</div>
	<div class="row">
		<div class="col s12 m12 l3">
			<div class="row">
				<div class="padding-largo">
					<p>Asistentes: <%=@docente.take.asistentes%></p>	
				</div>
			</div>
			<div class="row">
				<div class="padding-largo">
					<div class="row">
						<div class="col s5 m5 l12">
							<%= image_tag @docente.take.url_image, class: 'responsive-img' %>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col s12 m12 l9">
			<div class="row">
				<h4 class="center-align">
					Asistentes
				</h4>
			</div>
			<% @asistentes.each do |asistente| %>
				<div class="row">
					<%= image_tag asistente.url_image, class: 'rimg' %>
				</div>
			<%end%>
		</div>
	</div>
</div>